INSERT INTO Producto (Nombre, Descripcion, Imagen, Precio, Tipo) VALUES
('Pizza Margarita','Clásica con albahaca y tomate.','margaretaa.jpg',580,'Principal'),
('Pollo con verduras','Salteado de pollo y vegetales.','pollo_verduras.png',450,'Principal'),
('Hamburguesa Veggie','Lentejas y verduras.','burger_lentejas.png',390,'Principal'),
('Carne con papas','Clásico casero.','Carne_con_papas.jpg',520,'Principal'),
('Jugo Natural','Naranja recién exprimida.','jugon.jpg',180,'Bebida'),
('Milanesa de Pollo al Horno','Milanesa de pollo al horno con pan rallado integral y acompañada de puré de zapallo.','milanesaconzapallo.png',230,'Principal'),
('Chivito Light','Chivito con carne magra, pan integral, lechuga, tomate y huevo a la plancha sin aceite.','chivito.png',260,'Principal'),
('Empanadas Integrales de Verdura','Empanadas horneadas con masa integral y relleno de espinaca, ricota y zanahoria.','empanadas.png',180,'Principal'),
('Tarta de Acelga Light','Tarta casera con masa integral y relleno de acelga, cebolla y queso magro.','tarta de verdura.png',190,'Principal'),
('Ensalada Criolla','Tomate, cebolla, morrón y orégano fresco con aceite de oliva.','ensalada.png',130,'Principal'),
('Revuelto Gramajo Saludable','Papas al horno, huevo, cebolla, arvejas y jamón magro.','gramajo.png',210,'Principal'),
('Sopa de Calabaza y Zanahoria','Sopa cremosa con calabaza, zanahoria y un toque de jengibre.','sopa.png',160,'Principal'),
('Bowl de Lentejas Criollas','Lentejas con zapallo, cebolla, zanahoria y especias suaves.','lentejas.png',190,'Principal'),
('Hamburguesa Casera de Carne Magra','Hamburguesa de carne magra con pan integral, lechuga, tomate y aderezo natural.','hamburguesas2.png',220,'Principal'),
('Panqueques de Espinaca','Panqueques verdes rellenos de ricota y verduras al vapor.','panqueques de espinaca.png',160,'Principal'),

('Brownie Light','Brownie de cacao amargo con azúcar mascabo y nueces.','brownie.jpg',210,'Postre'),
('Ensalada de Frutas','Mix de frutas frescas de estación.','ensalada_frutas.png',150,'Postre'),
('Limonada con Menta','Refrescante limonada natural con hojas de menta fresca.','limonada_menta.jpg',160,'Bebida'),
('Agua saborizada de Frutos Rojos','Agua mineral infusionada con frutillas, arándanos y menta.','agua_frutosrojos.jpg',140,'Bebida'),
('Licuado de Banana y Avena','Licuado natural con leche descremada, banana y avena.','licuado_banana.png',190,'Bebida'),
('Cheesecake Light','Tarta fría de queso crema magro con base integral y coulis de frutos rojos.','cheesecake_light.png',230,'Postre'),
('Mousse de Chocolate Amargo','Mousse ligera con cacao amargo y endulzante natural.','mousse_choco.jpg',210,'Postre'),
('Yogur con Granola y Miel','Copa de yogur natural con granola casera y miel orgánica.','yogur_granola.jpg',180,'Postre');